### ISSUE TITLE
Multiple PDF's

### ISSUE THREAD

**Issue by BurtDS** [codedge/laravel-fpdf#45]
Hi, 

How does one create multiple pdfs? 
Example of what I'm trying to do:

        foreach ($orders as $order) {

            $orderPdf = new Fpdf('P','mm','A4');
            $orderPdf::AddPage();
            .....
            $orderPdf::Output('F', '...');

        }

But this results in a an Exception
FPDF error: The document is closed 

Many thanks !

**Comment by codedge** [comment]
This is some issue with the FPDF library. You can work around this like that:

```php
 $items = [1, 2, 3];

    foreach ( $items as $item ) {
        $pdf = new $fpdf();
        $pdf->AddPage();
        $pdf->SetFont('Courier', 'B', 18);
        $pdf->Cell(50, 25, 'Hello World!');
        $pdf->Output('F', $item . '.pdf');
    }
```

The issue is also reported multiple times on SO:

- [Here](https://stackoverflow.com/questions/20635410/fpdf-fails-to-create-multple-pdf-documents-when-the-same-image-file-is-used-in-a)
- [Here](https://stackoverflow.com/questions/48475899/fpdf-error-the-document-is-closed-in)
- Maybe more..
